In [4]:
import numpy as np
matrix1=np.array([[1,3],[2,6]])
matrix2=np.array([[5,9],[7,8]])
result_matrix = matrix1 + matrix2
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nResult Matrices:\n",result_matrix)

Matrix 1:
 [[1 3]
 [2 6]]

Matrix 2:
 [[5 9]
 [7 8]]

Result Matrices:
 [[ 6 12]
 [ 9 14]]
